### PR TITLE
fix broken caffe_converter

### PR DESCRIPTION
**Pull request by edgarriba**
In this PR the broken Caffe converter is fixed due to the fact that some users reported in https://github.com/tiny-dnn/tiny-dnn/issues/429 the bug in 5c2ab5b99abe4c283b290d9338aea080430261d7.

### CODE REVIEW

**Comment by edgarriba** [comment]
/cc @nyanp Could you explain why did you remove https://github.com/tiny-dnn/tiny-dnn/commit/5c2ab5b99abe4c283b290d9338aea080430261d7#diff-1201f4bcc000cb58d71ee51947e42774L149. ?
I realized that this is what makes the converter give wrong results.

**Comment by Randl** [comment]
LGTM.

Should we add simple real life test (one of reference caffe networks?) to make sure convertor works?

**Comment by edgarriba** [comment]
Probably, but which one? Usually big models require large space amount (not sure about our quota in Github)

**Comment by Randl** [comment]
The simplest one should be enough to find most critical bugs. And if caffe managed to fit it into repo, so can we I think

**Comment by Randl** [comment]
OK, the model is >200MB, we might add downloading to travis script and check for file existence in test

**Comment by edgarriba** [comment]
download 200Mb each time might slow down the testing process. Probably we could setup a small network e.g a simple mnist recognizer with few layers

**Comment by bhack** [comment]
I don't think will be hard to have a gitlfs for testing in the internal github network. What do you think?

**Comment by animetrics** [comment]
A couple comments. 

1.  Just a reminder to use git-lfs for binary files so that you don't end up with every version of the file when you clone.  Also, if you don't want to pull lfs files you can always temporarily disable the smudge filter when you clone. 

2.  Per my comment in #429 this commit does not seem to completely fix the problem.  Just thought I'd also mention it here.

**Pull request merged**
