### PR TITLE
Add some tests & update docs

### PR DESCRIPTION
**Pull request by nyanp**
- Add tests for serializers to confirm #356
- Update docs
- Fix serialization for concat-layer

### CODE REVIEW

**Comment by edgarriba** [comment]
@nyanp why is autodoc.py needed?

**Comment by nyanp** [comment]
@edgarriba 
It's painful to write "layer catalogue" by hand... so I decided to use simple python script to generate markdown docs from source code. You can see similar idea at:
https://github.com/fchollet/keras/blob/master/docs/autogen.py

**Comment by edgarriba** [comment]
looks good overall, just check typo error in constructor arguments

**Comment by nyanp** [comment]
@edgarriba 
Thanks :) could you point out where I have a typo?

**Comment by edgarriba** [comment]
for typo I mean that arguments from the generated docs are not alligned

**Pull request merged**
