### PR TITLE
add NNPackInitializer, update NNPack backend, fix broken tests and warnings

### PR DESCRIPTION
**Pull request by edgarriba**
- add NNPackInitializer as a singleton in order to have a global variable to check if nnpack is initialized.
- update NNPack codes: found a bug in inference -> replaced by output. /cc @azsane 
- fix maxpool and fully connected broken tests
- fix some warnings

### CODE REVIEW

**Comment by bhack** [comment]
If we need this singleton thread safe we requite [VS 2015](https://msdn.microsoft.com/en-au/library/hh567368.aspx#concurrencytable)

**Comment by azsane** [comment]
@edgarriba inference has a bug? Can you provide more detail?

And I just digged into output function found that 
```
enum nnp_status nnp_convolution_output(
	enum nnp_convolution_algorithm algorithm,
	size_t batch_size,
	size_t input_channels,
	size_t output_channels,
	struct nnp_size input_size,
	struct nnp_padding input_padding,
	struct nnp_size kernel_size,
	const float input[],
	const float kernel[],
	const float bias[],
	float output[],
	pthreadpool_t threadpool,
	struct nnp_profile* profile);
```

implementation
```
const struct nnp_size output_size = {
		.width = input_padding.left + input_size.width + input_padding.right - kernel_size.width + 1,
		.height = input_padding.top + input_size.height + input_padding.bottom - kernel_size.height + 1
	};
```
there is no *output_sampling* (or stride) provided  so it will compute incorrect value when conv has stride more than 1

**Comment by edgarriba** [comment]
@azsane Are you sure that your tests pass? I'm getting a segfault with nnp_convolution_inference

http://pastebin.com/ua9gMuYy

@Maratyszcza Did you notice similar error before?

**Comment by azsane** [comment]
@edgarriba 
Yes ,all 30 tests were passed.May be machine or enviroment related?

since nnp_kwt8x8_3x3_and_stream.avx2 cause SIGSEGV,a simple way can bypass this
change algorithm in conv2d_op_nnpack.h (I ran test with algorithm auto not the one changed below)
```
inline nnp_convolution_algorithm nnp_algorithm() {
    return nnp_convolution_algorithm_auto; //change this to nnp_convolution_algorithm_implicit_gemm
}
``` 

this algorithm doesn't use any avx2 related function and I use it in a converted caffemodel for googlenet.

The reason why I use the algorithm ,it's that on some machines auto one was quite slow than others(expecially on kernel size 3*3).Then it's unbelievable that gemm is fast than auto!

You can change algorithm to gemm and perform origin tests to see if it's correct.

**Comment by edgarriba** [comment]
@azsane I've tried with that flag and I end up at this exception: 
https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/core/kernels/conv2d_op_nnpack.h#L124

with a status error == 15 : https://github.com/Maratyszcza/NNPACK/blob/master/include/nnpack.h#L44

**Comment by azsane** [comment]
@edgarriba 
error code =15 ?
that's nnp_status_invalid_pooling_stride returned by validate_pooling_arguments

But this function is called by pool related function.Is conv test or pool test report this error ?

**Comment by edgarriba** [comment]
I'm trying this: ./test/tiny_dnn_test --gtest_filter=convolutional.fprop_nnp

**Comment by Maratyszcza** [comment]
@edgarriba `found a bug in inference -> replaced by output.` What is the bug in inference?

**Comment by edgarriba** [comment]
@Maratyszcza I'm not sure if it's a bug or what it is but as I mention before I got the following:
    -  `nn_convolution_inference`:
              `nnp_convolution_algorithm_implicit_auto` -> segfault
              `nnp_convolution_algorithm_implicit_gemm` -> status error == 15 (related pool error)
    -  `nn_convolution_output`:
              `nnp_convolution_algorithm_implicit_auto` -> OK
              `nnp_convolution_algorithm_implicit_gemm` -> need to check yet

**Comment by Maratyszcza** [comment]
@edgarriba I checked the code, and it is impossible: `nnp_convolution_inference` never returns `nnp_status_invalid_pooling_stride`. Only pooling functions return this error code.

**Comment by edgarriba** [comment]
@Maratyszcza now is okay, solved.
My bad ... I had an older version .so file installed. Thanks anyway.

**Pull request merged**
