### PR TITLE
add Google cpplint.py check after success build

### PR DESCRIPTION
**Pull request by edgarriba**

### CODE REVIEW

**Comment by Randl** [comment]
Should we run cpplint as pre-commit hook maybe?

**Comment by edgarriba** [comment]
@Randl that's another option as future feature. The problem is that right now there's a lot of work to do until we have a "clean" code. I'm preparing a small bash script just to print warnings. Do you have time take part of the work? Is a good way to check and understand part of the library :-)

**Comment by Randl** [comment]
@edgarriba I actually use IDE-included autoformat for my projects. It's very flexible and allow to process big amount of code fast and not to care about code formatting while coding.

I believe that if set properly it can solve most code style problems in one run

**Comment by edgarriba** [comment]
@Randl if you can do it automatic it will be great! Anyways, I'll merge this PR.

**Comment by Randl** [comment]
@edgarriba  I'll give it a try

**Comment by Randl** [comment]
@edgarriba here's what I got after running code style tool - https://github.com/Randl/tiny-cnn/tree/auto_code_style

**Comment by edgarriba** [comment]
@Randl it's too heavy ... 
look: https://github.com/Randl/tiny-cnn/blob/2867230d18ffde224a10dda88ef1c21bdec84d69/test/test_convolutional_layer.h#L39

Maybe you can configure it in order to have a specific format. At some point I searched tools to do it without good results. For this reason I started to modify files by hand. The most practical tool I found was using Sublime or Atom that can highlight from cpplint.

**Comment by Randl** [comment]
@edgarriba for some reason it didn't catch up `picotest`'s macros. Fixed

**Comment by edgarriba** [comment]
https://github.com/Randl/tiny-cnn/blob/auto_code_style/test/test_target_cost.h#L89-L93

still not convincing me

**Comment by Randl** [comment]
https://github.com/Randl/tiny-cnn/tree/auto_code_style_2 one more attempt

**Comment by edgarriba** [comment]
in some cases looks better.
Could you impose to have a maximum line width of 80?

Let's do the following: I'll merge this PR with cpplint.py and the testing script.
After that open a new PR with auto style and we modify from there. Agree?

**Comment by Randl** [comment]
@edgarriba If there are some places where autoformatting performs really bad, there is possibility to use comment markers to turn it off and on. I'll open a new PR and we'll discuss it there.

**Comment by edgarriba** [comment]
@Randl cool!

**Comment by patrikhuber** [comment]
Any reason why you're not using clang-format with a .clang-format file in
the repo? It's kind of the go-to tool for code formatting. Integrates
nicely into VS and other editors too.

**Comment by edgarriba** [comment]
@patrikhuber 
After some discussion we'll introduce clan-format. Check this https://github.com/tiny-dnn/tiny-dnn/pull/363

**Pull request merged**
