### PR TITLE
replacing picotests with gtests 

### PR DESCRIPTION
**Pull request by Randl**
Added gtest. https://github.com/tiny-dnn/tiny-dnn/issues/242

### CODE REVIEW

**Comment by patrikhuber** [comment]
@Randl Did you consider my comment in #242? If you want to switch to GTest, I think its sources should be included into tiny-dnn and it should be built with the tests, for a variety of reasons. Let me know in case I'm wrong.

**Comment by Randl** [comment]
@patrikhuber My code checkouts gtest from github

**Comment by edgarriba** [comment]
@Randl Could you move Download project into tiny-dnn/cmake?

**Comment by patrikhuber** [comment]
@Randl Ok, I see what DownloadProject is doing now. Can we really not get by with just `ExternalProject_Add`? Every additional script adds a complexity overhead to the build. Adding a whole new 3rd party tool just to use a unit test framework is a bit... yea... unfortunate. At this point, if it was my own project, I would really strongly consider Catch - header-only and no other overhead like building or other build scripts necessary.

**Comment by edgarriba** [comment]
@patrikhuber To use Catch we need to rewrite test codes. Maybe in a future we can give it a shot. Other priorities now.

**Comment by bhack** [comment]
Catch it is interesting but actually we don't have the bandwidth to rewrite tests cause the todo list it is quite busy. Better Gtest that picotest to have now.

**Comment by patrikhuber** [comment]
Sure. I'm just advocating for less complexity, whatever you decide to do.

**Comment by bhack** [comment]
@patrikhuber /off topic/ Do you want to take any bullet on the to do list? ;)

**Comment by patrikhuber** [comment]
@bhack Hehehe! I've been considering for quite a while, but never got around to it - I'm just too busy with my own PhD and 3D face fitting software (particularly now that I'm in my last 6 months). Actually the feature I'd like to see most in tiny-dnn is a sparse AutoEncoder :-) I think a sparsity constraint/layer is still missing. In any way, I'll let you guys know if I can take up on any tasks - sorry that it's not now.

**Comment by Randl** [comment]
@edgarriba yeah sure, I was considering it, but then thought that it'll be better to keep licence and readme and so put it into third party. 
@patrikhuber  well as for me simple script to checkout dependency isn't that critical, given we can keep all the tests

**Comment by Randl** [comment]
@nyanp @bhack  @edgarriba Any problem to merge?

**Comment by edgarriba** [comment]
one test do not pass
https://ci.appveyor.com/project/tinydnn/tiny-dnn/build/master-328/job/1ipwdyssouo6xlmv#L757

**Comment by edgarriba** [comment]
@Randl check my review comment.
You should consider to add this [lines](https://github.com/dmonopoly/gtest-cmake-example/blob/master/CMakeLists.txt#L53) in order to be able to call the `make test` command

**Comment by edgarriba** [comment]
@Randl 
Please also rebase from master to check that tests pass with double precision 10a02710a929986fcdc36ac14d080eaf4cd3839a

**Comment by edgarriba** [comment]
@Randl  thx. Very preciate contribution!

**Pull request merged**
