### PR TITLE
rename tiny_dnn backend to custom

### PR DESCRIPTION
**Pull request by edgarriba**

### CODE REVIEW

**Comment by beru** [comment]
In this case, custom means custom-made or customizable?
I've thought ex-tiny_dnn (now custom) backend as a reference backend.

**Comment by edgarriba** [comment]
@beru custom stands for custom-made. Do you think is not clear the rename?

**Comment by bhack** [comment]
Is it considered a fallback engine? Internal? I don't think that custom is one of the best naming ;)

**Comment by nyanp** [comment]
"internal" or "native" seems good for me :)

**Comment by edgarriba** [comment]
oki, native sounds good. I'll rename again

**Comment by bhack** [comment]
native could be mislead to the native code concept of not compiled langauges

**Comment by edgarriba** [comment]
generic?

**Comment by bhack** [comment]
I think that it is internal.. if we consider that a fallback (I.e. In the case I don't want any external library) we could call fallback

**Comment by patrikhuber** [comment]
Fallback also has a slightly negative conotation (i.e. "If all else fails, use this, but it will not be optimal"). Is this the case? If not, "internal" might be the best and most neutral name!

**Comment by edgarriba** [comment]
internal then, because the backends do not follow any rule to consider a fallback case

**Comment by edgarriba** [comment]
And talking about names convention: backends or engines ?

**Comment by bhack** [comment]
This is more diffucult :)

**Comment by patrikhuber** [comment]
"backend" sounds more natural to me - it's a backend (mostly linear algebra I suppose), that does computation. I don't think I'd really call it an "engine".

**Comment by bhack** [comment]
Others have called engines https://github.com/caffe2/caffe2/blob/master/caffe2/contrib/nnpack/nnpack_ops.cc#L260

**Pull request merged**
