### PR TITLE
Add serialization_buddy class to simplify friend declarations

### PR DESCRIPTION
**Pull request by beru**
Hi, this PR simplifies friend declarations in layer classes and it also externalizes serialization functions of `tiny_dnn::index3d` and `tiny_dnn::core::connection_table` classes.

### CODE REVIEW

**Comment by edgarriba** [comment]
@beru Is this PR in the line to remove or support decoupled activations from base layers?

**Comment by beru** [comment]
@edgarriba This PR is a sequel to #499 . `nodes`, `sequential`, `graph` classes still have internal serialization functions. so I'd like to update them later.

Talking about decoupling activation function from layer classes, I've noticed it isn't very easy to update the library, so I've been postponing the task.

**Comment by edgarriba** [comment]
@beru ok, let me know to merge it.

**Comment by edgarriba** [comment]
LGTM

**Pull request merged**
