### PR TITLE
Modify docs as per new activation API.

### PR DESCRIPTION
**Pull request by karandesai-96**
This PR changes code snippets in existing user docs as per the new activation API. This shall be tentatively the last PR before `feat/decouple_activations` gets properly merged into master.

### CODE REVIEW

**Comment by karandesai-96** [comment]
This bug is not reproducible by me locally. Travis failed due to 503 error, maybe a rebuild is required to see if the problem persists or was it a Travis problem itself.

**Comment by beru** [comment]
@karandesai-96 Please close and reopen the PR.
http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by karandesai-96** [comment]
@beru Done, I think it was a Travis problem. The build passed now. Time to bring the new API to master :rocket:

**Comment by karandesai-96** [comment]
I have rechecked all the differences between `feat/decouple_activations` and `master`, I think that after this PR is merged, we can push the new API to master.

**Pull request merged**
