### PR TITLE
update appveyor.yml to test with Visual Studio 2017

### PR DESCRIPTION
**Pull request by beru**
This PR updates `appveyor.yml` file to add builds with Visual Studio 2017.

### CODE REVIEW

**Comment by beru** [comment]
@edgarriba @bhack I updated `appveyor.yml` file to check VS2017 builds. As you can see, they fail currently after merging #917. If we remove xtensor with #947, we can successfully build with VS2017.

**Comment by beru** [comment]
@edgarriba @bhack This branch cannot be merged before #947.
And running 4 AppVeyor jobs will take about an hour, so they need to be optimized later.

I also want to add debug builds jobs (but will skip running tests with debug builds).

**Comment by bhack** [comment]
Another solution to evaluate https://ai.intel.com/intel-ngraph/

**Comment by beru** [comment]
I rejected #947 so merging this PR is impossible so I'll close this PR too.

**Pull request closed without merging**
