### PR TITLE
Enable Coverity-Scan API token in Travis

### PR DESCRIPTION
**Pull request by nyanp**
This is continued from #531. This PR replaces dummy API token with encrypted token for coverity scan-build.

### CODE REVIEW

**Comment by Randl** [comment]
I suppose to change notification email, and also branch. Master probably would mean checks are performed too often.

**Comment by nyanp** [comment]
@Randl It's up to you to change your notification settings :) Any suggestions to avoid interrupting our mailbox?

**Comment by Randl** [comment]
Well there is that site, https://www.kill-the-newsletter.com/ , which converts emails to RSS

**Comment by edgarriba** [comment]
is there any way to show results in a badge? https://shields.io/

**Comment by Randl** [comment]
I don't think so

**Comment by edgarriba** [comment]
well I see this: https://img.shields.io/coverity/scan/3997.svg
however not sure which output gives

**Comment by nyanp** [comment]
Coverity allows us to submit 4 builds/day.
https://scan.coverity.com/faq#frequency

We might need to separate the coverity build to ```coverity_scan``` branch and invoke build by hand (as they recommend at https://scan.coverity.com/faq#frequency) in order to avoid build breaking due to the API restriction.

I met an another problem around TBB with clang (clang 3.5.0 couldn't find ```std::is_tribially_copyable``` in the latest version of TBB https://travis-ci.org/tiny-dnn/tiny-dnn/jobs/214276470), but it should be treated as an another issue. I'll investigate the problem tomorrow.

**Comment by bhack** [comment]
Keras removed coverity cause was not satisfied by the quality of the service.. probably clang static coverage is enough..

**Comment by nyanp** [comment]
@bhack 
After struggling with that, I reached to the similar mind to Keras team... Anyway I think it's ok to keep ```coverity_scan``` branch as is and we should remove coverity API from master branch.

**Comment by nyanp** [comment]
@edgarriba 
> I think it's ok to keep coverity_scan branch as is and we should remove coverity API from master branch.

What do you think about removing the coverity build from master branch?

**Comment by edgarriba** [comment]
go ahead

**Comment by nyanp** [comment]
ok👌

**Pull request merged**
