### PR TITLE
add asinh activation function

### PR DESCRIPTION
**Pull request by lakshayg**

### CODE REVIEW

**Comment by lakshayg** [comment]
Hello all. I am trying to add `asinh` activation to `tiny-dnn`. I have made the changes but some unrelated tests seem to fail for no reason. 

```
[  FAILED  ] integration.gradient_check6 // appveyor
[  FAILED  ] integration.train2 // travis
```

Even when building the master branch, I first get errors as `<chrono>` is not included. After fixing that error, everything compiles and runs but running `tiny_dnn_test` gives me the following errors:

```
[  FAILED  ] quantized_convolutional.fprop
```

Could someone suggest what could be done.

**Comment by srk97** [comment]
@lakshayg Apply cpplint on `display.h`

**Comment by lakshayg** [comment]
@srk97  cpplint asks me to remove `<chrono>` but it is required to build `display.h`

```
➜  tiny-dnn git:(master) ✗ cpplint tiny_dnn/io/display.h
tiny_dnn/io/display.h:13:  <chrono> is an unapproved C++11 header.  [build/c++11] [5]
Done processing tiny_dnn/io/display.h
Total errors found: 1
```

Here is a snippet from `display.h` (clearly shows that <chrono> is needed)

```
#pragma once

#include <iostream>  // for ostream, cout, etc
#include <string>    // for string

namespace tiny_dnn {

class timer {
 public:
  timer() : t1(std::chrono::high_resolution_clock::now()) {}
  float_t elapsed() {
    return std::chrono::duration_cast<std::chrono::duration<float_t>>(
             std::chrono::high_resolution_clock::now() - t1)
      .count();
  }
```

**Comment by srk97** [comment]
@lakshayg we use c++14.

**Comment by lakshayg** [comment]
@srk97 I am using cmake to build the project. I checked and I can see that the build commands have `--std=c++14`. So I guess C++14 is not the issue. I am using g++ 5.4.0

**Comment by srk97** [comment]
@lakshayg 
```tiny_dnn/io/display.h:13:  <chrono> is an unapproved C++11 header.  [build/c++11] [5]
Done processing tiny_dnn/io/display.h
Total errors found: 1```
See the version there?

**Comment by lakshayg** [comment]
@srk97 I saw it has c++11, but that was the error message given by cpplint and has nothing to do with the build process. Is there a way to run cpplint in c++14 mode?

**Comment by srk97** [comment]
@lakshayg you're using `chrono` as `std::chrono`. The std namespace takes care of the usage. You need not include chrono

**Comment by edgarriba** [comment]
@lakshayg what's the status this PR?

**Comment by lakshayg** [comment]
@edgarriba Will try and update the PR by the end of next week.

**Comment by lakshayg** [comment]
I have updated the commit

**Comment by lakshayg** [comment]
Can one of the maintainers have a look, I am getting the following failure and I'm unable to reproduce this locally

screenshot from 2017-12-19 21-36-06

```
[----------] Global test environment tear-down
[==========] 287 tests from 32 test cases ran. (30476 ms total)
[  PASSED  ] 286 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] integration.train2
 1 FAILED TEST
```

**Comment by beru** [comment]
@lakshayg Just restarted the failed job.

This problem happens a lot actually. #909

**Comment by lakshayg** [comment]
Has someone been able to figure out the reason for these failures?

**Comment by beru** [comment]
@lakshayg Please rebase the branch so that I can merge.

**Comment by lakshayg** [comment]
@beru Done

**Comment by beru** [comment]
@lakshayg Please apply clang-format to `tiny_dnn/tiny_dnn.h` file.

Though I'm not sure what is wrong with the diff... it looks totally OK.
https://github.com/tiny-dnn/tiny-dnn/pull/891/commits/2f93170034341c4127954de9acbff8101c4b02a2#diff-308324af2ff351c1b1ceaf7d80e862b4

@edgarriba Please reconsider using clang-format with CI jobs. And, you said you would post a reply to #911 but you still haven't.

**Comment by lakshayg** [comment]
@beru  I ran clang-format but it does not change anything

**Comment by beru** [comment]
@lakshayg How did you run clang-format? By the way, [here](https://github.com/beru/tiny-cnn/commit/39dbb1204df6866577a902409435cab59943e264)'s the result which I obtained it so I suppose the procedures you took must be different from what I did. Taking this opportunity, I'd like to explain it.

- At the root of the repository, run `scripts/clang-format.sh` file with your terminal
  - The script specifically uses `clang-format-4.0` so install it before running the script.
 - If you're using Windows, you may use git bash for the terminal and you need to tweak the script file a little bit (Enclosing the path variables by double-quotes).

**Comment by lakshayg** [comment]
I used "clang-format -i tiny_dnn/tiny_dnn.h" to format the file. Thanks for explaining how it should have been done. I tried the procedure you just explained but it also does not seem to make any difference. I am attaching a screenshot of the same.

screenshot from 2018-02-19 07-27-39

For now, I am just manually making the changes so that clang-format is happy.

**Comment by beru** [comment]
@lakshayg I examined and found out the cause. You removed empty lines L39 and L42 from `tiny_dnn/tiny_dnn.h` and that made include statements consecutive.

You may see `SortIncludes:    true` option in `.clang-format` file. so... I guess how it goes.

**Comment by lakshayg** [comment]
Thanks @beru

**Pull request merged**
