### PR TITLE
separate serialization and deserialization

### PR DESCRIPTION
**Pull request by beru**
This PR covers the problem mentioned in #420 .
mainly @nyanp and @bhack Could you please review the change? If you noticed any problems, please feel free to let me know and I'll do my best to fix them.

### CODE REVIEW

**Comment by beru** [comment]
Here are build times I collected with Visual Studio

program built  | master <br> branch | master branch <br> without nn.load | serialization_deserialization <br> branch
-- | -------  | -------------------------- | -----------------------------
example_mnist_test | 45369 ms | 5960 ms | 36630 ms
example_mnist_train | 46186 ms | 9173 ms | 20812 ms

**Comment by bhack** [comment]
Do you have also the memory footprint?

**Comment by nyanp** [comment]
@beru 
Nice, looks fine :) Did you check if mnist train/test still work correctly?

**Comment by beru** [comment]
@nyanp Yes, I did it briefly. It would be great if you could check it as well.

**Comment by beru** [comment]
@bhack I collected what you asked for on the PR branch (using `-ftime-report -fmem-report` you taught me).
[make_example_mnist_test.txt](https://github.com/tiny-dnn/tiny-dnn/files/614765/make_example_mnist_test.txt)
[make_example_mnist_train.txt](https://github.com/tiny-dnn/tiny-dnn/files/614766/make_example_mnist_train.txt)

program built  | time | memory
-- | ------------ | -----------------
example_mnist_test | 41.35 sec | 1102M
example_mnist_train | 18.28 sec | 695M

gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by bhack** [comment]
Interesting metering but I see testing it is double of training.

**Comment by beru** [comment]
Yes, it is very slow. It needs to be improved a lot.

**Comment by nyanp** [comment]
@beru
I've checked. LGTM :)

**Pull request merged**
