### PR TITLE
remove xtensor

### PR DESCRIPTION
**Pull request by beru**
This PR removes xtensor related code from the library.
#939 is related.

### CODE REVIEW

**Comment by edgarriba** [comment]
@beru I'm okay with it, but what's the alternative then ?

**Comment by edgarriba** [comment]
@beru @bhack maybe it's enough with a dlpack like representation ?
https://github.com/dmlc/dlpack

**Comment by beru** [comment]
> what's the alternative then ?

@edgarriba I'd like to find very easy approach. I grepped with `tensor_t` keyword and 1110 lines were printed. So if we choose thorough modification approach, it may take years.

**Comment by bhack** [comment]
Probably could be to adopt Dlpack tensor and use TVM ops. So that we could remove many internal implementations.

**Comment by bhack** [comment]
A more drastic approach is to just design our NNVM network graph and let to use TVM ops. See https://github.com/dmlc/nnvm/blob/master/docs/how_to/deploy.md

**Comment by bhack** [comment]
If you want take a look to this intro https://aws.amazon.com/it/blogs/machine-learning/introducing-nnvm-compiler-a-new-open-end-to-end-compiler-for-ai-frameworks/

**Comment by beru** [comment]
@bhack If I understand correctly, relying on NNVM and TVM means this library will not be header only nor dependency-free. Is that correct?

**Comment by bhack** [comment]
We can see NNVM basically as a NN compiler so tinydnn could be a c++11 header only frontend. If you see here NNVM could consume and deploy already from many frontends https://github.com/dmlc/nnvm/tree/master/tutorials

**Comment by bhack** [comment]
So with this drastic option there could be something like from_tinydnn

**Comment by beru** [comment]
@bhack I briefly checked several `from_*` scripts at https://github.com/dmlc/nnvm/tree/master/tutorials.
Basically what the scripts do is loading famous library/framework's model files then compilation and execution follow. So compatibility through data-formats is there. But is that the thing we're talking about?

NNVM already has Python and C++ bindings so I imagine modifying this library is like rebuilding a trailer truck using small electric car. Let's admit we ain't got no :rugby_football:  :rugby_football: of :metal: to overcome such technical difficulties and debts, shall we?

**Comment by bhack** [comment]
You can check two comments at https://github.com/tiny-dnn/tiny-dnn/issues/921#issuecomment-358707547. We actually don't have graph optimizzation, gpu ops, and many optimized cpu ops on different hardware. So I don't think that we have bandwidth to implement all this things in tinydnn.

**Comment by beru** [comment]
@bhack @edgarriba 

I fully admit having interoperability with NNVM compiler is what must be done in future.

But I fear disposing self-contained nature might be too drastic. So I'd like to reuse current implementation for the sake of preserving header-only, dependency free, stand-alone traits of this library .

Therefore, I suppose we need to separate front-end and back-end of this library further to achieve those different objectives.

As I wrote in previous comments, replacing `tensor_t` to something else within this library seems not very easy. So I say using dlpack's DLTensor looks favourable but not achievable as a short-term goal.

But I think that's OK as long as this library will not directly handle TVM Runtime. If my understanding is correct, only TVM Runtime is DLPack compatible. NNVM compiler is backed by TVM stack but NNVM C/C++ APIs aren't.

And let's not talk about using TVM runtime from this library as we already have many objectives.

**Comment by beru** [comment]
> But I think that's OK as long as this library will not directly handle TVM Runtime. If my understanding is correct, only TVM Runtime is DLPack compatible. NNVM compiler is backed by TVM stack but NNVM C/C++ APIs aren't.

This might be wrong. nnvm python code uses nnvm C-api and tvm python code which means compilation stage is handled by TVM.

**Comment by beru** [comment]
@bhack @edgarriba What I want to say is it's not easy to deeply operate with NNVM and TVM with low-level APIs. NNVM frontends are written in Python but tiny-dnn doesn't have Python API.

**Comment by bhack** [comment]
Another alternative initiative that was backed also by Tensorflow is https://arxiv.org/pdf/1711.03016.pdf. Check the paper to see the differences against TVM and XLA.

**Comment by beru** [comment]
@bhack 

> Probably it is not too far. What do you think of dmlc/nnvm#343?

The movement is great but it's still under development and not ready yet. Even if NNVM/TVM C++ compiler API will be ready in future, that doesn't mean this library can automatically interact with it. 

As I grew older, I've come to realize estimating the amount of work with just wild guess and prior knowledge alone does not always lead to favorable results. 

> Another alternative initiative that was backed also by Tensorflow is https://arxiv.org/pdf/1711.03016.pdf. 
> Check the paper to see the differences against TVM and XLA.

It seems to me NNKit and DLVM IR aren't interoperable from C/C++ by design. 
Aside from that, talented compiler devs are awesome.  :open_mouth:

**Comment by bhack** [comment]
Without being connected with a strong upstream project for scheduling and ops tinydnn will be not practical from an operative point of view. 
So for me we could remove xtensor and merge this but actually I don't see any internal roadmap to cover this topics or bandwidth1 to develop internal solutions. If we remove xtensors what other kind of solution we will have?

**Comment by bhack** [comment]
Another solution to evaluate https://ai.intel.com/intel-ngraph/

**Comment by bhack** [comment]
http://ngraph.nervanasys.com/docs/cpp/

**Comment by bhack** [comment]
This a is a nice overview https://arxiv.org/pdf/1801.08058.pdf

**Comment by beru** [comment]
@bhack Then what about reverting #917 ?

If you anyhow want to keep xtensor in this library, that's fine. But I'm not really sure the meaning of having dependency to other library if it's not actually used (at least in master branch) and doesn't replace `tensor_t` at all.

From what you say I think it sounds pretty amazing that keep using the library will may somehow give us NNVM/TVM interoperability in auto manner even though integration development has stopped more than half an year.

**Comment by beru** [comment]
> If we remove xtensors what other kind of solution we will have?

@bhack Changing `tensor_t` from typedef of `std::vector<std::vector<float_t>>` to custom type that is compatible with current code would be good for first step. We need to carry out this task with least efforts because of the heavy use of `tensor_t`.

Actually, it's enjoyable to see names of many good looking libraries/frameworks/compilers. But without the actual process, I wonder what the outcome would be.

**Comment by bhack** [comment]
Edgar what do you think? Probably xtensor will not solve scheduling and ops at level of this other solutions.

**Comment by beru** [comment]
@bhack I have an impression that there's no strong incentive to remove xtensor so I close this PR.

**Pull request closed without merging**
