### PR TITLE
Reduce duplicated code

### PR DESCRIPTION
**Pull request by beru**
Hi, this PR reduces duplicated code.
#740 and #745 are related.

### CODE REVIEW

**Comment by nishnik** [comment]
:+1:

**Comment by edgarriba** [comment]
@nishnik do you have any other contribution in mind? A lot of stuff will be happening during the few months. So would be nice to discuss before coding

**Comment by nishnik** [comment]
Nothing in particular, though you can suggest me some.
Till now, I just looked around the codebase and was looking for new things to do and implement.

**Comment by edgarriba** [comment]
@nishnik you could try to fix this https://github.com/tiny-dnn/tiny-dnn/pull/730

**Comment by nishnik** [comment]
Okay I will do it.

**Comment by edgarriba** [comment]
check the comments above and how we solve it for the other kernels

**Pull request merged**
