### PR TITLE
fixed bugs in caffe converter example

### PR DESCRIPTION
**Pull request by Jiaolong**
The current caffe converter example is not fully tested. Mainly fixed bugs in:
- CMakefiles: enable compile caffe_converter example
- caffe_converter.cpp: updated the code with latest tiny-dnn

### CODE REVIEW

**Comment by edgarriba** [comment]
@Jiaolong 
thx for the contribution !

**Comment by Jiaolong** [comment]
@edgarriba
I just tested it with caffe bvlc reference model, however, an error occured when running in release mode. It shows `Illegal instruction     (core dumped)`.

In debug mode, everything is fine. I tried to locat the error and it turns out that the crash came from this line:
https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/util/random.h#L68

I haven't solved this problem. Could you please help me on this? I have compared the cmake c++ flags of release and debug, but got no hint.

**Comment by nyanp** [comment]
@Jiaolong 
Removing ```CNN_USE_AVX``` flag would solve the problem if you use AMD processor. See:  https://github.com/tiny-dnn/tiny-dnn/issues/245

**Comment by Jiaolong** [comment]
Thanks a lot! Setting USE_AVX=OFF, it works perfectly! I use Intel CPU though, `Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz`.

**Pull request merged**
