### PR TITLE
caffe converter: add support for loading BatchNorm from trained model

### PR DESCRIPTION
**Pull request by festlv**
Currently caffe converter supports creating BatchNorm layer from prototxt file. However, it did not support loading this weights for this layer from protobinary file.

This PR adds the missing support.

Also, it adds Accuracy and Split layer types to be ignored- they are present in the protobinary file but are not relevant for reconstructing the net.

### CODE REVIEW

**Comment by edgarriba** [comment]
@festlv is there any way to test this patch?

**Comment by Randl** [comment]
@festlv Can you please and some tests for added functionality?

**Comment by festlv** [comment]
Yes, will try to do it this week.

**Comment by Randl** [comment]
ping @festlv

**Comment by festlv** [comment]
Sorry, long week :)
Will try this week.

**Pull request merged**
