### PR TITLE
Add model serialization

### PR DESCRIPTION
**Pull request by nyanp**
Initial version of serialization method (#276). In this version, serialization of conv/deconv/quantized layer isn't implemented to avoid confliction between other PRs

TODO:
- [x] add unit test for each layer
- [x] serialize graph connection
- [x] integrate with weight serialization
- [x] fix MacOS build error

### CODE REVIEW

**Comment by nyanp** [comment]
MacOS build failed because of cereal's known issue.
https://github.com/USCiLab/cereal/issues/339

Related:
http://cplusplus.github.io/LWG/lwg-defects.html#2193

I need to fix it before merging.

**Comment by zhangqianhui** [comment]
@nyanp I think this layer (partial_connected_layer) can be deleted ! #289

**Comment by edgarriba** [comment]
@zhangqianhui 
 if you have time, go ahead with migration from partial_connected inheritance to feedforward

**Comment by zhangqianhui** [comment]
@edgarriba  I have a try !

**Pull request merged**
