### PR TITLE
Add public predict method for vector of tensors

### PR DESCRIPTION
**Pull request by reunanen**
For completeness. Want to `fprop` multiple samples in parallel (in particular because of how `fully_connected_op_custom` and `conv2d_op_custom` are parallelized at the moment).

### CODE REVIEW

**Comment by edgarriba** [comment]
@reunanen Could you provide a small test for this?

**Comment by reunanen** [comment]
@edgarriba Ok, will try to find the time to do this.

**Comment by reunanen** [comment]
@edgarriba Added a test.

**Comment by edgarriba** [comment]
LGDT

@nyanp review also and merge

**Comment by nyanp** [comment]
Looks good.

@reunanen 
Thanks again for your contribution! :)

**Pull request merged**
