### PR TITLE
Decouple activation function template parameter from layer classes

### PR DESCRIPTION
**Pull request by beru**
Hi, this PR decouples activation function template parameter from layer classes.

### CODE REVIEW

**Comment by beru** [comment]
I've noticed some of layer classes still don't have `serialize` and `load_and_construct` methods implementation. So they cannot be serialized/deserialized

Talking about changes in this PR, declaring static variable for activation function might be a bit cumbersome. Another way I can think of is passing enum value to layer class constructor that selects activation function.

And calling virtual methods of function class inside long loop is not efficient and slow.
But I'd like to improve that later.

**Comment by beru** [comment]
This PR introduces breaking changes so let me explain about them.

tiny-dnn specifies acitivation function type by layer class template parameter, like this.
```cpp
    nn << convolutional_layer<tan_h>(32, 32, 5, 1, 6,  // C1, 1@32x32-in, 6@28x28-out
            padding::valid, true, 1, 1, backend_type)
```

But in that way, the number of the combinations of layers classes and activation function classes gets big at compile-time and that resulted in long compilation and linking time with cereal library.

And making python interface is also hard with layer class template parameter because possible combination of layer classes and activation functions need to be instantiated for bindings.

Now in the PR branch, activation function is specified as a 1st parameter of layer class constructor.
```cpp
    static tan_h tan_h;
    nn << convolutional_layer(tan_h, 32, 32, 5, 1, 6,  // C1, 1@32x32-in, 6@28x28-out
            padding::valid, true, 1, 1, backend_type)
```
But using static variable all the time for activation functions may probably be unfavorable for library users.
So if that's the problem, passing enum type value to select activation function inside constructor would be an alternative way.

---

Talking about serialization, I added a method to get name of activation function to `activation::function` classes and also added `get_function` global function to return an instance of activation function specified by its name.

`CNN_REGISTER_LAYER_WITH_ACTIVATION` macro is not used anymore and `load_and_construct` and `serialize` methods in extended layer classes that have activation function are changed. Activation functions are saved/restored using its name. This change breaks backward compatibility of serialized data.

Please feel free to post comments.

**Comment by edgarriba** [comment]
@beru couple of comments:
1) I'd would like to keep backward compatibility
2) Instead of enums I would remove activations completely from the interface in order to behave like this
```cpp
nn << conv << relu << maxpool << fully << relu;
```

**Comment by beru** [comment]
> couple of comments:
> 1. I'd would like to keep backward compatibility
> 2. Instead of enums I would remove activations completely from the interface in order to behave like this
> ```
> nn << conv << relu << maxpool << fully << relu;
> ```

@edgarriba I'll update serialize/deserilize routines to keep backward compatibility in this branch.

And you mentioned `when there's no cereal in the library root it cannot be compiled even if you define the CNN_NO_SERIALIZATION macro`, if that's really true, is it OK to resolve the problem in this branch? Or should I create another PR?

Talking about the change to define a neural network graph, I have a lot of questions to ask...
- Should activation function classes inherit from `node` in that case?
- What if invalid combination of layers and functions are specified? Should the library throw exceptions?
- Do you want me to add that huge change in this PR??

**Comment by beru** [comment]
@edgarriba Some layer classes still don't have the implementation of `serialize` and `load_and_construct` methods. Do you think it's OK to implement them now? or should I postpone it?

**Comment by Randl** [comment]
> But in that way, the number of the combinations of layers classes and activation function classes gets big at compile-time and that resulted in long compilation and linking time with cereal library.

That's sounds like speculative thing to say, usual usage is only activation function for the whole network

**Comment by beru** [comment]
@Randl Talking about build time issue, please refer #420, #421
If you uncomment calls to `network::load` or `network::save`, or comment out  `CNN_REGISTER_LAYER_WITH_ACTIVATIONS` in `CNN_REGISTER_LAYER_WITH_ACTIVATIONS` and build the programs. You can check the impact.

**Comment by beru** [comment]
> That's sounds like speculative thing to say, usual usage is only activation function for the whole network

@Randl I still don't understand about this sentence. Can you please tell me more specificly?

**Comment by Randl** [comment]
>  I still don't understand about this sentence. Can you please tell me more specificly?

@beru You suppose that since we compiler gets to specialize each layer for each activation, it increases compilation time significantly. I believe, that in real-life app, people will use a single activation function, which means a single specialization for each layer.

**Comment by beru** [comment]
@Randl The problem is when deserializing neural network model from serialized file.
Current library uses `CNN_REGISTER_LAYER_WITH_ACTIVATIONS` macro to instantiate all possible combinations of layers and activation functions for deserialization.

Please compare build time of `tiny-dnn/examples/mnist/test.cpp` before and after commenting out `network::load` call.

**Comment by beru** [comment]
@Randl 
For instance, `examples/mnist/test.cpp` does not define a neural network model at compile time unlike `examples/mnist/train.cpp`. Maybe @nyanp changed the code in that way with the use of `cereal` library.

While that dynamic model loading feature is really good to have, it needs `cereal` library.
Please look at `examples/CMakeLists.txt`. Only when `USE_SERIALIZER` is ON, `example_mnist_train` and `example_mnist_test` and `example_deconv_train` are used.

I think we should relax that limitation. What about moving `construct_net` function into separate file and included the file when `USE_SERIALIZER` is OFF with `examples/mnist/test.cpp`?, so that it can work even without cereal library.

**Comment by beru** [comment]
I will close this PR. This approach (activation function as constructor parameter for layer classes) is abandoned. Future plan would be making activation functions as independent layer extended classes. 
Issue #484 and `feat/decouple_activations`  branch is created for further work.

**Pull request closed without merging**
