### PR TITLE
fix 'num_hidden_units' not defined in examples/main.cpp:305

### PR DESCRIPTION
**Pull request by NiklasRosenstein**

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Interesting , I didn't know CMake had such a feature. And I thought it would be a revolutionary feature in [Craftr](https://github.com/craftr-build/craftr), lol.

Let me know if I should revert the last commit.

**Comment by edgarriba** [comment]
@NiklasRosenstein thx for the pull request. It's fine for now.
However, if you could dig into @bhack's solution with a new pull request, it would be awesome. 😃

**Comment by bhack** [comment]
I prefer to merge this now cause there is a bugfix in one commit and if  @NiklasRosenstein wants to contribute a more elegant solution for the data path he can open a new PR.

**Comment by edgarriba** [comment]
@NiklasRosenstein thx for your contribution! :+1:

**Comment by NiklasRosenstein** [comment]
You're welcome. Unfortunately I don't have much experience with CMake, if I find the time I'll check it out though. Since tiny-dnn is so easy to use, it might be just as simple to set up a simple CMake file.

I could definitely provide a Craftr build script if anyones interested. 😁 Would be as simple as

```python
# tiny-dnn.examples

from craftr.loaders import external_file

files = Namespace()
files.directory = buildlocal('train_data')
files.train_labels_idx1 = external_file("https://github.com/tiny-dnn/tiny-dnn/raw/531ab8dd984de525cc74e5695f8c8fe65924a3cd/data/train-labels.idx1-ubyte", directory = files.directory)
files.train_images_idx3 = external_file("https://github.com/tiny-dnn/tiny-dnn/raw/531ab8dd984de525cc74e5695f8c8fe65924a3cd/data/train-images.idx3-ubyte", directory = files.directory)
files.t10k_labels_idx1 = external_file("https://github.com/tiny-dnn/tiny-dnn/raw/531ab8dd984de525cc74e5695f8c8fe65924a3cd/data/t10k-labels.idx1-ubyte", directory = files.directory)
files.t10k_images_idx3 = external_file("https://github.com/tiny-dnn/tiny-dnn/raw/531ab8dd984de525cc74e5695f8c8fe65924a3cd/data/t10k-images.idx3-ubyte", directory = files.directory)

load_module('lang.cxx.*')

main = cxx_binary(
  inputs = cpp_compile(
    sources = [local('main.cpp')],
    include = [local('..')]
  ),
  output = 'example'
)

run = runtarget(main, files.directory)
```

**Pull request merged**
