### PR TITLE
Repair benchmarks build.

### PR DESCRIPTION
**Pull request by evilmucedin**
I found that benchmarks build is broken in master.

- Repair benchmarks build after enforcing C++14.
- Repair benchmarks build.

### CODE REVIEW

**Comment by beru** [comment]
@nyanp @edgarriba  I'd like to re-run failed appveyor build for the purpose of reviewing pull requests but I'm unable to do so. For travis-ci, I can freely restart build/job. I wish the same thing would be possible for appveyor.

**Comment by beru** [comment]
I've locally confirmed that "Visual Studio 14 2015" Win32 Release builds successfully.
So I suspect there might be instability in AppVeyor. Though travis-ci jobs also fail time to time, I've been wondering what is the cause of this...

**Comment by beru** [comment]
I've confirmed all CI jobs succesfully finished.

**Comment by evilmucedin** [comment]
Thank you :)

**Pull request merged**
