### PR TITLE
Fix invalid read/write problems detected by valgrind

### PR DESCRIPTION
**Pull request by beru**
Hi, this PR fixes invalid memory accesses detected by Valgrind. #514

### CODE REVIEW

**Comment by Randl** [comment]
Have you run Valgrind to check if it is really fixed or should I do that?

**Comment by beru** [comment]
I've run Valgrind on the tests written in `#include "test_convolutional_layer.h"` with Debug build.
If you could kindly inspect the bugs, that would be very helpful.

**Comment by Randl** [comment]
Fix confirmed. Good to merge

**Comment by edgarriba** [comment]
@beru please rebase from master

**Comment by beru** [comment]
@edgarriba rebased and force-pushed.

**Comment by beru** [comment]
@edgarriba rebased and force-pushed again.

**Pull request merged**
