### PR TITLE
Rename cnn_size_t to serial_size_t

### PR DESCRIPTION
**Pull request by Randl**
As was discussed in https://github.com/tiny-dnn/tiny-dnn/issues/399 `cnn_size_t` should be renamed.

### CODE REVIEW

**Comment by nyanp** [comment]
@Randl 
LGTM 👍 

@beru and @pansk pointed out on gitter that there's an excessive use of cnn_size_t. Since we can just use ```size_t``` instead of ```sereal_size_t``` where serialization isn't the matter, I'll do further improvement after this PR is merged. Thanks!

**Comment by pansk** [comment]
Is the serialization going to be an external project (dnn-serialize)?
If so, I think we can safely change all occurrences of serial_size_t back to size_t, and let the external lib to do any conversion.

**Comment by edgarriba** [comment]
@pansk maybe it's a good idea to have it as an external project since after introducing it to the pipeline the compilation time increased a lot and it's really annoying.

**Comment by pansk** [comment]
I have two reasons why an external serialization project would be a good idea:
- If we can do serialization outside the library it means that the library is fully configurable from outside (and, so, is complete)
- if we need to introduce additional dependencies just for serialization (e.g. protobuf, some json serialization library, boost::ptree or anything else), we can keep the main library "clean".

**Pull request merged**
