### PR TITLE
android ndk - start

### PR DESCRIPTION
**Pull request by zhangqianhui**

### CODE REVIEW

**Comment by edgarriba** [comment]
@zhangqianhui 
Are this *.*~ files really needed?

**Comment by zhangqianhui** [comment]
@edgarriba maybe , I will change some file.

**Comment by zhangqianhui** [comment]
Why? some error
@edgarriba

**Comment by edgarriba** [comment]
@zhangqianhui 
rebase from master to fix appveyor issue

**Comment by edgarriba** [comment]
@zhangqianhui 
I still see temporal files, binaries and absolutes paths. 

Besides, how do you guarantee that users could compile this piece of code?
Can we cross-compile it via TravisCI? /cc @bhack

**Comment by bhack** [comment]
It is needed to add android in Travis. See https://docs.travis-ci.com/user/languages/android

**Comment by edgarriba** [comment]
@bhack nice! let's see if we can mix languages in TravisCI.

@zhangqianhui could you go ahead adding at least "cross compiling test" with Android?

**Comment by zhangqianhui** [comment]
@edgarriba 
OK ，Tomorrow I will do it .

**Comment by zhangqianhui** [comment]
@edgarriba  
Now I don't know how to use travis ci to do the test ? so wait a moment , I must learn it .

**Comment by edgarriba** [comment]
@zhangqianhui 
try to install TravisCI in local and setup the tests there first
https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

Try to find out how to mix in the same travis.yml C++ and Android

**Comment by zhangqianhui** [comment]
@edgarriba ok.

**Comment by edgarriba** [comment]
@zhangqianhui 
check this link for multi language with TravisCI
 https://github.com/travis-ci/travis-ci/issues/4090

**Comment by edgarriba** [comment]
@zhangqianhui any update?

**Comment by zhangqianhui** [comment]
@edgarriba Recetly I'm busy in other things. Wait a few days.

**Comment by edgarriba** [comment]
@zhangqianhui Any update?

**Comment by zhangqianhui** [comment]
@edgarriba  Now i have  learned the new version and trying  to use ndk to compile it.

**Comment by bhack** [comment]
@sh1r0 are you interested in this?

**Comment by bhack** [comment]
We could evaluate to use the same approach of [IOS example](https://github.com/tiny-dnn/tiny-dnn/blob/master/examples/ios/readme.md) with https://github.com/ruslo/polly/pull/96

**Comment by Randl** [comment]
@zhangqianhui ping. Are you interested to continue?

**Comment by zhangqianhui** [comment]
@Randl you can close it .

**Pull request closed without merging**
