### PR TITLE
Fix build error with Emscripten

### PR DESCRIPTION
**Pull request by blackccpie**
- corrected missing forwarding operator for rvalue reference, which caused broken emscripten build.

### CODE REVIEW

**Comment by edgarriba** [comment]
@blackccpie is it bug or what's the behavior before this?

**Comment by edgarriba** [comment]
related to https://github.com/tiny-dnn/tiny-dnn/issues/854

**Comment by blackccpie** [comment]
@edgarriba : sorry indeed I forgot to mention the related issue

**Comment by blackccpie** [comment]
sorry I unintentionally closed the PR

**Pull request merged**
